[package]
name = "riscv_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
riscv_protocol = { path = "../riscv_protocol", default-features = false, features = ["alloc"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
postcard = { version = "1.0", default-features = false, features = ["alloc"] }

[features]
default = []
alloc = []
