// megafunction wizard: %ALTDDIO_BIDIR%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: ALTDDIO_BIDIR 

// ============================================================
// File Name: mf_ddio_bidir_12.v
// Megafunction Name(s):
// ALTDDIO_BIDIR
//
// Simulation Library Files(s):
// altera_mf
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 18.1.1 Build 646 04/11/2019 SJ Lite Edition
// ************************************************************


//Copyright (C) 2019  Intel Corporation. All rights reserved.
//Your use of Intel Corporation's design tools, logic functions 
//and other software and tools, and any partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Intel Program License 
//Subscription Agreement, the Intel Quartus Prime License Agreement,
//the Intel FPGA IP License Agreement, or other applicable license
//agreement, including, without limitation, that your use is for
//the sole purpose of programming logic devices manufactured by
//Intel and sold by Intel or its authorized distributors.  Please
//refer to the applicable agreement for further details, at
//https://fpgasoftware.intel.com/eula.


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module mf_ddio_bidir_12 (
datain_h,
datain_l,
inclock,
oe,
outclock,
dataout_h,
dataout_l,
padio);

input[11:0]  datain_h;
input[11:0]  datain_l;
input  inclock;
input  oe;
input  outclock;
output[11:0]  dataout_h;
output[11:0]  dataout_l;
inout[11:0]  padio;

wire [11:0] sub_wire0;
wire [11:0] sub_wire1;
wire [11:0] dataout_h = sub_wire0[11:0];
wire [11:0] dataout_l = sub_wire1[11:0];

altddio_bidirALTDDIO_BIDIR_component (
.datain_h (datain_h),
.datain_l (datain_l),
.inclock (inclock),
.oe (oe),
.outclock (outclock),
.padio (padio),
.dataout_h (sub_wire0),
.dataout_l (sub_wire1),
.aclr (1'b0),
.aset (1'b0),
.combout (),
.dqsundelayedout (),
.inclocken (1'b1),
.oe_out (),
.outclocken (1'b1),
.sclr (1'b0),
.sset (1'b0));
defparam
ALTDDIO_BIDIR_component.extend_oe_disable = "OFF",
ALTDDIO_BIDIR_component.implement_input_in_lcell = "OFF",
ALTDDIO_BIDIR_component.intended_device_family = "Cyclone V",
ALTDDIO_BIDIR_component.invert_output = "OFF",
ALTDDIO_BIDIR_component.lpm_hint = "UNUSED",
ALTDDIO_BIDIR_component.lpm_type = "altddio_bidir",
ALTDDIO_BIDIR_component.oe_reg = "UNREGISTERED",
ALTDDIO_BIDIR_component.power_up_high = "OFF",
ALTDDIO_BIDIR_component.width = 12;


endmodule
