[package]
name = "cpu-sim"
version = "0.1.0"
edition = "2021"

[dependencies]
riscv_core = { path = "../riscv_core" }
riscv_protocol = { path = "../riscv_protocol" }
riscv_shared = { path = "../riscv_shared" }
clap = { version = "4.4", features = ["derive"] }
elf = "0.7"
log = "0.4"
env_logger = "0.10"
serde = { version = "1.0", features = ["derive"] }
postcard = "1.0"
image = "0.25"

[dev-dependencies]
sim-tests = { path = "../sim-tests" }
